### ISSUE TITLE
Roundup Week of 6 December 2021

### ISSUE THREAD

**Issue by murillol** [wpmarketingteam/Marcomms-Meetups#30]
Set aside some time this week to check out these online #WordPress meetups:

WordPress Portland (USA) on 7 December 2021, 2.00am UTC (6 December 6.00pm PST). Discover what Dart Sass is, why you should be aware of it and just how powerful your CSS can become!
Sign-Up:  https://www.meetup.com/pdx-wp/events/282048370/

WordPress Pittsburgh (USA) on 7 December 2021, 11.00pm UTC (6.00pm EST). Learn how to create a plugin and add new features to your plugins while you develop.
Sign-Up: https://www.meetup.com/Pittsburgh-WordPress-Developers-Designers/events/281739750/

WordPress Toronto (Canada) on 9 December 2021, 12.00am UTC (8 December 7.00pm EST). Explore the Gutenberg Editor, and how its block based approach has affected WordPress design and development.
Sign-Up:  https://www.meetup.com/WPToronto/events/282385570/

WordPress San Fernando Valley (USA) on 11 December 2021, 10.00pm UTC (2.00pm PST). Learn all about WAI- ARIA (Web Accessibility Initiative - Accessible Rich Internet Applications) and how to implement ARIA in your WordPress site.
RSVP: https://www.meetup.com/WordPress-San-Fernando-Valley-Meetup/events/282338814/

#OnlineWPMeetup #a11y #Gutenberg

**[Published Post](https://www.linkedin.com/posts/make-wordpress-marketing-team_meetup-we-are-what-we-do-activity-6873423641699205120-rmz8)**

**Comment by murillol** [comment]
@yvettesonneveld ready!

**Comment by yvettesonneveld** [comment]
@murillol Done!
https://docs.google.com/spreadsheets/d/1VDcXnchfIQqVjtgzCHFU6Tmr2RlYPYYm8gjN4zAAoEQ/edit#gid=426460521
